### ISSUE TITLE
String formatting doesn't remove quotes from strings passed in from template parameters

### ISSUE THREAD

**Issue by uwx** [zeta-group/ZDCode#2]
When deriving a template, if the template formats a string with `f{}`, if the format parameter is a template parameter and it is passed in quotes, the formatting will emit the quotes as-is, which breaks the string. Passing the template parameter unquoted does not work as an alternative because special characters like  `.` break the parser.
Note that this works fine when done directly e.g: `f{"prefix " "Na me" " suffix"}`

Using ZDCode 2.13.3.

## Repro

Sample code:
```cpp
class<Name> SampleTemplate extends Weapon {
  set obituary to f{"prefix " Name " suffix"};
}

derive Sample2 as SampleTemplate::(".");
```

Expected result:
```cpp
Actor Sample2 : Weapon
{
    obituary "prefix . suffix"
}
```

Actual result:
```cpp
Actor Sample2 : Weapon
{
    obituary "prefix "." suffix"
}
```

**Comment by wallabra** [comment]
The format concatenator was designed to be used to make class names dynamic when instantiating a template. I will look into the formatting of string literals.

**Comment by wallabra** [comment]
This does highlight that the parsing code needs a cleanup. I'll fix this when I'm back home. But I am planning to rewrite this whole thing in Rust. The bright side is it won't require Python to run anymore then!
